language: node_js
node_js:
 - "8.9.4"
branches:
 only:
 - build
before_script:
 - npm install -g ionic cordova
script:
 - ionic cordova build android -prod
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
   branch: build
 local_dir: www