version: 2.0

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: pwd
      - run: npm install ionic cordova
      - run: npm install
      - run: gem install fastlane
      - run: fastlane add_plugin ionic
      - run: fastlane build_debug

workflows:
  version: 2.0
  build:
    jobs:
      - build
      