version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: npm install -g ionic cordova
      - run: npm install
      - run: gem install fastlane
      - run: fastlane add_plugin ionic
      - run: fastlane build_debug

workflows:
  version: 2.0
  build:
    jobs:
      - build